language: python
python:
    - "3.4"
    - "3.3"
    - "3.2"
    - "2.7"
    - "pypy"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install --allow-all-external --allow-unverified ipaddr -e .[test]; fi
    - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then pip install -e .[test]; fi
script: make test
